export enum UserRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  INVENTORY_MANAGER = "INVENTORY_MANAGER",
  WAREHOUSE_OPERATOR = "WAREHOUSE_OPERATOR",
  SALES_REP = "SALES_REP",
  CUSTOMER = "CUSTOMER"
}

export enum OrderStatus {
  PENDING = "PENDING",
  RESERVED = "RESERVED",
  CONFIRMED = "CONFIRMED",
  PROCESSING = "PROCESSING",
  PICKED = "PICKED",
  PACKED = "PACKED",
  SHIPPED = "SHIPPED",
  DELIVERED = "DELIVERED",
  CANCELLED = "CANCELLED",
  RETURN_REQUESTED = "RETURN_REQUESTED",
  RETURNED = "RETURNED",
  REFUNDED = "REFUNDED"
}

export enum PaymentStatus {
  PENDING = "PENDING",
  AUTHORIZED = "AUTHORIZED",
  PAID = "PAID",
  PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
  REFUNDED = "REFUNDED",
  FAILED = "FAILED"
}

export enum StockAdjustmentReason {
  RESTOCK = "RESTOCK",
  SALE_RESERVATION = "SALE_RESERVATION",
  ORDER_FULFILLED = "ORDER_FULFILLED",
  ORDER_CANCELLED_RESTOCK = "ORDER_CANCELLED_RESTOCK",
  DAMAGED_GOODS = "DAMAGED_GOODS",
  RETURN_RESTOCK = "RETURN_RESTOCK",
  INVENTORY_AUDIT_CORRECTION = "INVENTORY_AUDIT_CORRECTION",
  WAREHOUSE_TRANSFER = "WAREHOUSE_TRANSFER",
  EXPIRED = "EXPIRED"
}

export enum ProductStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  ARCHIVED = "ARCHIVED",
  DISCONTINUED = "DISCONTINUED"
}

export enum AlertSeverity {
  INFO = "INFO",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL"
}

export enum CustomerTier {
  STANDARD = "STANDARD",
  SILVER = "SILVER",
  GOLD = "GOLD",
  PLATINUM = "PLATINUM",
  WHOLESALE = "WHOLESALE"
}

export enum ABCCategory {
  CLASS_A = "CLASS_A", // High value, 80% revenue
  CLASS_B = "CLASS_B", // Moderate value, 15% revenue
  CLASS_C = "CLASS_C"  // Low value, 5% revenue
}
