// Department: Professional Broadcast Audio & Mixers
// Standard Catalog SKU Master Definition

export interface AudioBroadcastSKU {
  sku: string;
  name: string;
  department: string;
  category: string;
  hsTariffCode: string;
  weightGrams: number;
  lengthMm: number;
  widthMm: number;
  heightMm: number;
  basePrice: number;
  costPrice: number;
  leadTimeDays: number;
  minimumOrderQuantity: number;
  safetyStock: number;
  binLocation: string;
  voltageRating?: string;
  operatingTempRange: string;
  complianceCertifications: string[];
}

export const AUDIO_BROADCAST_REGISTRY: AudioBroadcastSKU[] = [
  {
    sku: "SKU-AUD-0001",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-001",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.101",
    weightGrams: 475,
    lengthMm: 182,
    widthMm: 141,
    heightMm: 41,
    basePrice: 209.92,
    costPrice: 131.2,
    leadTimeDays: 6,
    minimumOrderQuantity: 2,
    safetyStock: 9,
    binLocation: "Aisle-02-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0002",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-002",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.102",
    weightGrams: 500,
    lengthMm: 184,
    widthMm: 142,
    heightMm: 42,
    basePrice: 227.84,
    costPrice: 142.4,
    leadTimeDays: 7,
    minimumOrderQuantity: 3,
    safetyStock: 10,
    binLocation: "Aisle-03-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0003",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-003",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.103",
    weightGrams: 525,
    lengthMm: 186,
    widthMm: 143,
    heightMm: 43,
    basePrice: 245.76,
    costPrice: 153.6,
    leadTimeDays: 8,
    minimumOrderQuantity: 1,
    safetyStock: 11,
    binLocation: "Aisle-04-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0004",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-004",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.104",
    weightGrams: 550,
    lengthMm: 188,
    widthMm: 144,
    heightMm: 44,
    basePrice: 263.68,
    costPrice: 164.8,
    leadTimeDays: 9,
    minimumOrderQuantity: 2,
    safetyStock: 12,
    binLocation: "Aisle-05-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0005",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-005",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.105",
    weightGrams: 575,
    lengthMm: 190,
    widthMm: 145,
    heightMm: 45,
    basePrice: 281.6,
    costPrice: 176.0,
    leadTimeDays: 10,
    minimumOrderQuantity: 3,
    safetyStock: 13,
    binLocation: "Aisle-06-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0006",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-006",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.106",
    weightGrams: 600,
    lengthMm: 192,
    widthMm: 146,
    heightMm: 46,
    basePrice: 299.52,
    costPrice: 187.2,
    leadTimeDays: 11,
    minimumOrderQuantity: 1,
    safetyStock: 14,
    binLocation: "Aisle-07-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0007",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-007",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.107",
    weightGrams: 625,
    lengthMm: 194,
    widthMm: 147,
    heightMm: 47,
    basePrice: 317.44,
    costPrice: 198.39999999999998,
    leadTimeDays: 12,
    minimumOrderQuantity: 2,
    safetyStock: 15,
    binLocation: "Aisle-08-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0008",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-008",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.108",
    weightGrams: 650,
    lengthMm: 196,
    widthMm: 148,
    heightMm: 48,
    basePrice: 335.36,
    costPrice: 209.6,
    leadTimeDays: 13,
    minimumOrderQuantity: 3,
    safetyStock: 16,
    binLocation: "Aisle-09-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0009",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-009",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.109",
    weightGrams: 675,
    lengthMm: 198,
    widthMm: 149,
    heightMm: 49,
    basePrice: 353.28,
    costPrice: 220.8,
    leadTimeDays: 14,
    minimumOrderQuantity: 1,
    safetyStock: 17,
    binLocation: "Aisle-10-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0010",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-010",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.110",
    weightGrams: 700,
    lengthMm: 200,
    widthMm: 150,
    heightMm: 50,
    basePrice: 371.2,
    costPrice: 232.0,
    leadTimeDays: 5,
    minimumOrderQuantity: 2,
    safetyStock: 18,
    binLocation: "Aisle-01-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0011",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-011",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.111",
    weightGrams: 725,
    lengthMm: 202,
    widthMm: 151,
    heightMm: 51,
    basePrice: 389.12,
    costPrice: 243.2,
    leadTimeDays: 6,
    minimumOrderQuantity: 3,
    safetyStock: 19,
    binLocation: "Aisle-02-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0012",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-012",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.112",
    weightGrams: 750,
    lengthMm: 204,
    widthMm: 152,
    heightMm: 52,
    basePrice: 407.04,
    costPrice: 254.39999999999998,
    leadTimeDays: 7,
    minimumOrderQuantity: 1,
    safetyStock: 20,
    binLocation: "Aisle-03-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0013",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-013",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.113",
    weightGrams: 775,
    lengthMm: 206,
    widthMm: 153,
    heightMm: 53,
    basePrice: 424.96,
    costPrice: 265.6,
    leadTimeDays: 8,
    minimumOrderQuantity: 2,
    safetyStock: 21,
    binLocation: "Aisle-04-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0014",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-014",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.114",
    weightGrams: 800,
    lengthMm: 208,
    widthMm: 154,
    heightMm: 54,
    basePrice: 442.88,
    costPrice: 276.79999999999995,
    leadTimeDays: 9,
    minimumOrderQuantity: 3,
    safetyStock: 22,
    binLocation: "Aisle-05-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0015",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-015",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.115",
    weightGrams: 825,
    lengthMm: 210,
    widthMm: 155,
    heightMm: 40,
    basePrice: 460.8,
    costPrice: 288.0,
    leadTimeDays: 10,
    minimumOrderQuantity: 1,
    safetyStock: 8,
    binLocation: "Aisle-06-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0016",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-016",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.116",
    weightGrams: 850,
    lengthMm: 212,
    widthMm: 156,
    heightMm: 41,
    basePrice: 478.72,
    costPrice: 299.2,
    leadTimeDays: 11,
    minimumOrderQuantity: 2,
    safetyStock: 9,
    binLocation: "Aisle-07-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0017",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-017",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.117",
    weightGrams: 875,
    lengthMm: 214,
    widthMm: 157,
    heightMm: 42,
    basePrice: 496.64,
    costPrice: 310.4,
    leadTimeDays: 12,
    minimumOrderQuantity: 3,
    safetyStock: 10,
    binLocation: "Aisle-08-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0018",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-018",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.118",
    weightGrams: 900,
    lengthMm: 216,
    widthMm: 158,
    heightMm: 43,
    basePrice: 514.56,
    costPrice: 321.6,
    leadTimeDays: 13,
    minimumOrderQuantity: 1,
    safetyStock: 11,
    binLocation: "Aisle-09-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0019",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-019",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.119",
    weightGrams: 925,
    lengthMm: 218,
    widthMm: 159,
    heightMm: 44,
    basePrice: 532.48,
    costPrice: 332.79999999999995,
    leadTimeDays: 14,
    minimumOrderQuantity: 2,
    safetyStock: 12,
    binLocation: "Aisle-10-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0020",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-020",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.120",
    weightGrams: 950,
    lengthMm: 220,
    widthMm: 160,
    heightMm: 45,
    basePrice: 550.4,
    costPrice: 344.0,
    leadTimeDays: 5,
    minimumOrderQuantity: 3,
    safetyStock: 13,
    binLocation: "Aisle-01-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0021",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-021",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.121",
    weightGrams: 975,
    lengthMm: 222,
    widthMm: 161,
    heightMm: 46,
    basePrice: 568.32,
    costPrice: 355.2,
    leadTimeDays: 6,
    minimumOrderQuantity: 1,
    safetyStock: 14,
    binLocation: "Aisle-02-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0022",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-022",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.122",
    weightGrams: 1000,
    lengthMm: 224,
    widthMm: 162,
    heightMm: 47,
    basePrice: 586.24,
    costPrice: 366.4,
    leadTimeDays: 7,
    minimumOrderQuantity: 2,
    safetyStock: 15,
    binLocation: "Aisle-03-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0023",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-023",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.123",
    weightGrams: 1025,
    lengthMm: 226,
    widthMm: 163,
    heightMm: 48,
    basePrice: 604.16,
    costPrice: 377.59999999999997,
    leadTimeDays: 8,
    minimumOrderQuantity: 3,
    safetyStock: 16,
    binLocation: "Aisle-04-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0024",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-024",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.124",
    weightGrams: 1050,
    lengthMm: 228,
    widthMm: 164,
    heightMm: 49,
    basePrice: 622.08,
    costPrice: 388.79999999999995,
    leadTimeDays: 9,
    minimumOrderQuantity: 1,
    safetyStock: 17,
    binLocation: "Aisle-05-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0025",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-025",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.125",
    weightGrams: 1075,
    lengthMm: 230,
    widthMm: 165,
    heightMm: 50,
    basePrice: 640.0,
    costPrice: 400.0,
    leadTimeDays: 10,
    minimumOrderQuantity: 2,
    safetyStock: 18,
    binLocation: "Aisle-06-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0026",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-026",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.126",
    weightGrams: 1100,
    lengthMm: 232,
    widthMm: 166,
    heightMm: 51,
    basePrice: 657.92,
    costPrice: 411.2,
    leadTimeDays: 11,
    minimumOrderQuantity: 3,
    safetyStock: 19,
    binLocation: "Aisle-07-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0027",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-027",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.127",
    weightGrams: 1125,
    lengthMm: 234,
    widthMm: 167,
    heightMm: 52,
    basePrice: 675.84,
    costPrice: 422.4,
    leadTimeDays: 12,
    minimumOrderQuantity: 1,
    safetyStock: 20,
    binLocation: "Aisle-08-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0028",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-028",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.128",
    weightGrams: 1150,
    lengthMm: 236,
    widthMm: 168,
    heightMm: 53,
    basePrice: 693.76,
    costPrice: 433.59999999999997,
    leadTimeDays: 13,
    minimumOrderQuantity: 2,
    safetyStock: 21,
    binLocation: "Aisle-09-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0029",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-029",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.129",
    weightGrams: 1175,
    lengthMm: 238,
    widthMm: 169,
    heightMm: 54,
    basePrice: 711.68,
    costPrice: 444.79999999999995,
    leadTimeDays: 14,
    minimumOrderQuantity: 3,
    safetyStock: 22,
    binLocation: "Aisle-10-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0030",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-030",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.130",
    weightGrams: 1200,
    lengthMm: 240,
    widthMm: 170,
    heightMm: 40,
    basePrice: 729.6,
    costPrice: 456.0,
    leadTimeDays: 5,
    minimumOrderQuantity: 1,
    safetyStock: 8,
    binLocation: "Aisle-01-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0031",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-031",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.131",
    weightGrams: 1225,
    lengthMm: 242,
    widthMm: 171,
    heightMm: 41,
    basePrice: 747.52,
    costPrice: 467.2,
    leadTimeDays: 6,
    minimumOrderQuantity: 2,
    safetyStock: 9,
    binLocation: "Aisle-02-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0032",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-032",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.132",
    weightGrams: 1250,
    lengthMm: 244,
    widthMm: 172,
    heightMm: 42,
    basePrice: 765.44,
    costPrice: 478.4,
    leadTimeDays: 7,
    minimumOrderQuantity: 3,
    safetyStock: 10,
    binLocation: "Aisle-03-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0033",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-033",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.133",
    weightGrams: 1275,
    lengthMm: 246,
    widthMm: 173,
    heightMm: 43,
    basePrice: 783.36,
    costPrice: 489.59999999999997,
    leadTimeDays: 8,
    minimumOrderQuantity: 1,
    safetyStock: 11,
    binLocation: "Aisle-04-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0034",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-034",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.134",
    weightGrams: 1300,
    lengthMm: 248,
    widthMm: 174,
    heightMm: 44,
    basePrice: 801.28,
    costPrice: 500.79999999999995,
    leadTimeDays: 9,
    minimumOrderQuantity: 2,
    safetyStock: 12,
    binLocation: "Aisle-05-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0035",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-035",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.135",
    weightGrams: 1325,
    lengthMm: 250,
    widthMm: 175,
    heightMm: 45,
    basePrice: 819.2,
    costPrice: 512.0,
    leadTimeDays: 10,
    minimumOrderQuantity: 3,
    safetyStock: 13,
    binLocation: "Aisle-06-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0036",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-036",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.136",
    weightGrams: 1350,
    lengthMm: 252,
    widthMm: 176,
    heightMm: 46,
    basePrice: 837.12,
    costPrice: 523.2,
    leadTimeDays: 11,
    minimumOrderQuantity: 1,
    safetyStock: 14,
    binLocation: "Aisle-07-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0037",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-037",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.137",
    weightGrams: 1375,
    lengthMm: 254,
    widthMm: 177,
    heightMm: 47,
    basePrice: 855.04,
    costPrice: 534.4,
    leadTimeDays: 12,
    minimumOrderQuantity: 2,
    safetyStock: 15,
    binLocation: "Aisle-08-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0038",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-038",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.138",
    weightGrams: 1400,
    lengthMm: 256,
    widthMm: 178,
    heightMm: 48,
    basePrice: 872.96,
    costPrice: 545.5999999999999,
    leadTimeDays: 13,
    minimumOrderQuantity: 3,
    safetyStock: 16,
    binLocation: "Aisle-09-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0039",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-039",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.139",
    weightGrams: 1425,
    lengthMm: 258,
    widthMm: 179,
    heightMm: 49,
    basePrice: 890.88,
    costPrice: 556.8,
    leadTimeDays: 14,
    minimumOrderQuantity: 1,
    safetyStock: 17,
    binLocation: "Aisle-10-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0040",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-040",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.140",
    weightGrams: 1450,
    lengthMm: 260,
    widthMm: 140,
    heightMm: 50,
    basePrice: 908.8,
    costPrice: 568.0,
    leadTimeDays: 5,
    minimumOrderQuantity: 2,
    safetyStock: 18,
    binLocation: "Aisle-01-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0041",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-041",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.141",
    weightGrams: 1475,
    lengthMm: 262,
    widthMm: 141,
    heightMm: 51,
    basePrice: 926.72,
    costPrice: 579.2,
    leadTimeDays: 6,
    minimumOrderQuantity: 3,
    safetyStock: 19,
    binLocation: "Aisle-02-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0042",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-042",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.142",
    weightGrams: 1500,
    lengthMm: 264,
    widthMm: 142,
    heightMm: 52,
    basePrice: 944.64,
    costPrice: 590.4,
    leadTimeDays: 7,
    minimumOrderQuantity: 1,
    safetyStock: 20,
    binLocation: "Aisle-03-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0043",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-043",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.143",
    weightGrams: 1525,
    lengthMm: 266,
    widthMm: 143,
    heightMm: 53,
    basePrice: 962.56,
    costPrice: 601.5999999999999,
    leadTimeDays: 8,
    minimumOrderQuantity: 2,
    safetyStock: 21,
    binLocation: "Aisle-04-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0044",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-044",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.144",
    weightGrams: 1550,
    lengthMm: 268,
    widthMm: 144,
    heightMm: 54,
    basePrice: 980.48,
    costPrice: 612.8,
    leadTimeDays: 9,
    minimumOrderQuantity: 3,
    safetyStock: 22,
    binLocation: "Aisle-05-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0045",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-045",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.145",
    weightGrams: 1575,
    lengthMm: 270,
    widthMm: 145,
    heightMm: 40,
    basePrice: 998.4,
    costPrice: 624.0,
    leadTimeDays: 10,
    minimumOrderQuantity: 1,
    safetyStock: 8,
    binLocation: "Aisle-06-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0046",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-046",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.146",
    weightGrams: 1600,
    lengthMm: 272,
    widthMm: 146,
    heightMm: 41,
    basePrice: 1016.32,
    costPrice: 635.1999999999999,
    leadTimeDays: 11,
    minimumOrderQuantity: 2,
    safetyStock: 9,
    binLocation: "Aisle-07-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0047",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-047",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.147",
    weightGrams: 1625,
    lengthMm: 274,
    widthMm: 147,
    heightMm: 42,
    basePrice: 1034.24,
    costPrice: 646.4,
    leadTimeDays: 12,
    minimumOrderQuantity: 3,
    safetyStock: 10,
    binLocation: "Aisle-08-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0048",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-048",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.148",
    weightGrams: 1650,
    lengthMm: 276,
    widthMm: 148,
    heightMm: 43,
    basePrice: 1052.16,
    costPrice: 657.5999999999999,
    leadTimeDays: 13,
    minimumOrderQuantity: 1,
    safetyStock: 11,
    binLocation: "Aisle-09-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0049",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-049",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.149",
    weightGrams: 1675,
    lengthMm: 278,
    widthMm: 149,
    heightMm: 44,
    basePrice: 1070.08,
    costPrice: 668.8,
    leadTimeDays: 14,
    minimumOrderQuantity: 2,
    safetyStock: 12,
    binLocation: "Aisle-10-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0050",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-050",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.150",
    weightGrams: 1700,
    lengthMm: 280,
    widthMm: 150,
    heightMm: 45,
    basePrice: 1088.0,
    costPrice: 680.0,
    leadTimeDays: 5,
    minimumOrderQuantity: 3,
    safetyStock: 13,
    binLocation: "Aisle-01-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0051",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-051",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.151",
    weightGrams: 1725,
    lengthMm: 282,
    widthMm: 151,
    heightMm: 46,
    basePrice: 1105.92,
    costPrice: 691.1999999999999,
    leadTimeDays: 6,
    minimumOrderQuantity: 1,
    safetyStock: 14,
    binLocation: "Aisle-02-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0052",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-052",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.152",
    weightGrams: 1750,
    lengthMm: 284,
    widthMm: 152,
    heightMm: 47,
    basePrice: 1123.84,
    costPrice: 702.4,
    leadTimeDays: 7,
    minimumOrderQuantity: 2,
    safetyStock: 15,
    binLocation: "Aisle-03-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0053",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-053",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.153",
    weightGrams: 1775,
    lengthMm: 286,
    widthMm: 153,
    heightMm: 48,
    basePrice: 1141.76,
    costPrice: 713.5999999999999,
    leadTimeDays: 8,
    minimumOrderQuantity: 3,
    safetyStock: 16,
    binLocation: "Aisle-04-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0054",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-054",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.154",
    weightGrams: 1800,
    lengthMm: 288,
    widthMm: 154,
    heightMm: 49,
    basePrice: 1159.68,
    costPrice: 724.8,
    leadTimeDays: 9,
    minimumOrderQuantity: 1,
    safetyStock: 17,
    binLocation: "Aisle-05-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0055",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-055",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.155",
    weightGrams: 1825,
    lengthMm: 290,
    widthMm: 155,
    heightMm: 50,
    basePrice: 1177.6,
    costPrice: 736.0,
    leadTimeDays: 10,
    minimumOrderQuantity: 2,
    safetyStock: 18,
    binLocation: "Aisle-06-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0056",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-056",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.156",
    weightGrams: 1850,
    lengthMm: 292,
    widthMm: 156,
    heightMm: 51,
    basePrice: 1195.52,
    costPrice: 747.1999999999999,
    leadTimeDays: 11,
    minimumOrderQuantity: 3,
    safetyStock: 19,
    binLocation: "Aisle-07-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0057",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-057",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.157",
    weightGrams: 1875,
    lengthMm: 294,
    widthMm: 157,
    heightMm: 52,
    basePrice: 1213.44,
    costPrice: 758.4,
    leadTimeDays: 12,
    minimumOrderQuantity: 1,
    safetyStock: 20,
    binLocation: "Aisle-08-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0058",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-058",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.158",
    weightGrams: 1900,
    lengthMm: 296,
    widthMm: 158,
    heightMm: 53,
    basePrice: 1231.36,
    costPrice: 769.5999999999999,
    leadTimeDays: 13,
    minimumOrderQuantity: 2,
    safetyStock: 21,
    binLocation: "Aisle-09-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0059",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-059",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.159",
    weightGrams: 1925,
    lengthMm: 298,
    widthMm: 159,
    heightMm: 54,
    basePrice: 1249.28,
    costPrice: 780.8,
    leadTimeDays: 14,
    minimumOrderQuantity: 3,
    safetyStock: 22,
    binLocation: "Aisle-10-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0060",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-060",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.160",
    weightGrams: 1950,
    lengthMm: 300,
    widthMm: 160,
    heightMm: 40,
    basePrice: 1267.2,
    costPrice: 792.0,
    leadTimeDays: 5,
    minimumOrderQuantity: 1,
    safetyStock: 8,
    binLocation: "Aisle-01-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0061",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-061",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.161",
    weightGrams: 1975,
    lengthMm: 302,
    widthMm: 161,
    heightMm: 41,
    basePrice: 1285.12,
    costPrice: 803.1999999999999,
    leadTimeDays: 6,
    minimumOrderQuantity: 2,
    safetyStock: 9,
    binLocation: "Aisle-02-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0062",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-062",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.162",
    weightGrams: 2000,
    lengthMm: 304,
    widthMm: 162,
    heightMm: 42,
    basePrice: 1303.04,
    costPrice: 814.4,
    leadTimeDays: 7,
    minimumOrderQuantity: 3,
    safetyStock: 10,
    binLocation: "Aisle-03-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0063",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-063",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.163",
    weightGrams: 2025,
    lengthMm: 306,
    widthMm: 163,
    heightMm: 43,
    basePrice: 1320.96,
    costPrice: 825.5999999999999,
    leadTimeDays: 8,
    minimumOrderQuantity: 1,
    safetyStock: 11,
    binLocation: "Aisle-04-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0064",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-064",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.164",
    weightGrams: 2050,
    lengthMm: 308,
    widthMm: 164,
    heightMm: 44,
    basePrice: 1338.88,
    costPrice: 836.8,
    leadTimeDays: 9,
    minimumOrderQuantity: 2,
    safetyStock: 12,
    binLocation: "Aisle-05-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0065",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-065",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.165",
    weightGrams: 2075,
    lengthMm: 310,
    widthMm: 165,
    heightMm: 45,
    basePrice: 1356.8,
    costPrice: 848.0,
    leadTimeDays: 10,
    minimumOrderQuantity: 3,
    safetyStock: 13,
    binLocation: "Aisle-06-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0066",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-066",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.166",
    weightGrams: 2100,
    lengthMm: 312,
    widthMm: 166,
    heightMm: 46,
    basePrice: 1374.72,
    costPrice: 859.1999999999999,
    leadTimeDays: 11,
    minimumOrderQuantity: 1,
    safetyStock: 14,
    binLocation: "Aisle-07-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0067",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-067",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.167",
    weightGrams: 2125,
    lengthMm: 314,
    widthMm: 167,
    heightMm: 47,
    basePrice: 1392.64,
    costPrice: 870.4,
    leadTimeDays: 12,
    minimumOrderQuantity: 2,
    safetyStock: 15,
    binLocation: "Aisle-08-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0068",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-068",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.168",
    weightGrams: 2150,
    lengthMm: 316,
    widthMm: 168,
    heightMm: 48,
    basePrice: 1410.56,
    costPrice: 881.5999999999999,
    leadTimeDays: 13,
    minimumOrderQuantity: 3,
    safetyStock: 16,
    binLocation: "Aisle-09-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0069",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-069",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.169",
    weightGrams: 2175,
    lengthMm: 318,
    widthMm: 169,
    heightMm: 49,
    basePrice: 1428.48,
    costPrice: 892.8,
    leadTimeDays: 14,
    minimumOrderQuantity: 1,
    safetyStock: 17,
    binLocation: "Aisle-10-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0070",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-070",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.170",
    weightGrams: 2200,
    lengthMm: 320,
    widthMm: 170,
    heightMm: 50,
    basePrice: 1446.4,
    costPrice: 904.0,
    leadTimeDays: 5,
    minimumOrderQuantity: 2,
    safetyStock: 18,
    binLocation: "Aisle-01-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0071",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-071",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.171",
    weightGrams: 2225,
    lengthMm: 322,
    widthMm: 171,
    heightMm: 51,
    basePrice: 1464.32,
    costPrice: 915.1999999999999,
    leadTimeDays: 6,
    minimumOrderQuantity: 3,
    safetyStock: 19,
    binLocation: "Aisle-02-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0072",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-072",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.172",
    weightGrams: 2250,
    lengthMm: 324,
    widthMm: 172,
    heightMm: 52,
    basePrice: 1482.24,
    costPrice: 926.4,
    leadTimeDays: 7,
    minimumOrderQuantity: 1,
    safetyStock: 20,
    binLocation: "Aisle-03-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0073",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-073",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.173",
    weightGrams: 2275,
    lengthMm: 326,
    widthMm: 173,
    heightMm: 53,
    basePrice: 1500.16,
    costPrice: 937.5999999999999,
    leadTimeDays: 8,
    minimumOrderQuantity: 2,
    safetyStock: 21,
    binLocation: "Aisle-04-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0074",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-074",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.174",
    weightGrams: 2300,
    lengthMm: 328,
    widthMm: 174,
    heightMm: 54,
    basePrice: 1518.08,
    costPrice: 948.8,
    leadTimeDays: 9,
    minimumOrderQuantity: 3,
    safetyStock: 22,
    binLocation: "Aisle-05-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0075",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-075",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.175",
    weightGrams: 2325,
    lengthMm: 330,
    widthMm: 175,
    heightMm: 40,
    basePrice: 1536.0,
    costPrice: 960.0,
    leadTimeDays: 10,
    minimumOrderQuantity: 1,
    safetyStock: 8,
    binLocation: "Aisle-06-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0076",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-076",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.176",
    weightGrams: 2350,
    lengthMm: 332,
    widthMm: 176,
    heightMm: 41,
    basePrice: 1553.92,
    costPrice: 971.1999999999999,
    leadTimeDays: 11,
    minimumOrderQuantity: 2,
    safetyStock: 9,
    binLocation: "Aisle-07-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0077",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-077",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.177",
    weightGrams: 2375,
    lengthMm: 334,
    widthMm: 177,
    heightMm: 42,
    basePrice: 1571.84,
    costPrice: 982.4,
    leadTimeDays: 12,
    minimumOrderQuantity: 3,
    safetyStock: 10,
    binLocation: "Aisle-08-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0078",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-078",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.178",
    weightGrams: 2400,
    lengthMm: 336,
    widthMm: 178,
    heightMm: 43,
    basePrice: 1589.76,
    costPrice: 993.5999999999999,
    leadTimeDays: 13,
    minimumOrderQuantity: 1,
    safetyStock: 11,
    binLocation: "Aisle-09-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0079",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-079",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.179",
    weightGrams: 2425,
    lengthMm: 338,
    widthMm: 179,
    heightMm: 44,
    basePrice: 1607.68,
    costPrice: 1004.8,
    leadTimeDays: 14,
    minimumOrderQuantity: 2,
    safetyStock: 12,
    binLocation: "Aisle-10-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0080",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-080",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.180",
    weightGrams: 2450,
    lengthMm: 340,
    widthMm: 140,
    heightMm: 45,
    basePrice: 1625.6,
    costPrice: 1016.0,
    leadTimeDays: 5,
    minimumOrderQuantity: 3,
    safetyStock: 13,
    binLocation: "Aisle-01-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0081",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-081",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.181",
    weightGrams: 2475,
    lengthMm: 342,
    widthMm: 141,
    heightMm: 46,
    basePrice: 1643.52,
    costPrice: 1027.1999999999998,
    leadTimeDays: 6,
    minimumOrderQuantity: 1,
    safetyStock: 14,
    binLocation: "Aisle-02-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0082",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-082",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.182",
    weightGrams: 2500,
    lengthMm: 344,
    widthMm: 142,
    heightMm: 47,
    basePrice: 1661.44,
    costPrice: 1038.4,
    leadTimeDays: 7,
    minimumOrderQuantity: 2,
    safetyStock: 15,
    binLocation: "Aisle-03-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0083",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-083",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.183",
    weightGrams: 2525,
    lengthMm: 346,
    widthMm: 143,
    heightMm: 48,
    basePrice: 1679.36,
    costPrice: 1049.6,
    leadTimeDays: 8,
    minimumOrderQuantity: 3,
    safetyStock: 16,
    binLocation: "Aisle-04-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0084",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-084",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.184",
    weightGrams: 2550,
    lengthMm: 348,
    widthMm: 144,
    heightMm: 49,
    basePrice: 1697.28,
    costPrice: 1060.8,
    leadTimeDays: 9,
    minimumOrderQuantity: 1,
    safetyStock: 17,
    binLocation: "Aisle-05-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0085",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-085",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.185",
    weightGrams: 2575,
    lengthMm: 350,
    widthMm: 145,
    heightMm: 50,
    basePrice: 1715.2,
    costPrice: 1072.0,
    leadTimeDays: 10,
    minimumOrderQuantity: 2,
    safetyStock: 18,
    binLocation: "Aisle-06-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0086",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-086",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.186",
    weightGrams: 2600,
    lengthMm: 352,
    widthMm: 146,
    heightMm: 51,
    basePrice: 1733.12,
    costPrice: 1083.1999999999998,
    leadTimeDays: 11,
    minimumOrderQuantity: 3,
    safetyStock: 19,
    binLocation: "Aisle-07-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0087",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-087",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.187",
    weightGrams: 2625,
    lengthMm: 354,
    widthMm: 147,
    heightMm: 52,
    basePrice: 1751.04,
    costPrice: 1094.4,
    leadTimeDays: 12,
    minimumOrderQuantity: 1,
    safetyStock: 20,
    binLocation: "Aisle-08-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0088",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-088",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.188",
    weightGrams: 2650,
    lengthMm: 356,
    widthMm: 148,
    heightMm: 53,
    basePrice: 1768.96,
    costPrice: 1105.6,
    leadTimeDays: 13,
    minimumOrderQuantity: 2,
    safetyStock: 21,
    binLocation: "Aisle-09-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0089",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-089",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.189",
    weightGrams: 2675,
    lengthMm: 358,
    widthMm: 149,
    heightMm: 54,
    basePrice: 1786.88,
    costPrice: 1116.8,
    leadTimeDays: 14,
    minimumOrderQuantity: 3,
    safetyStock: 22,
    binLocation: "Aisle-10-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0090",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-090",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.190",
    weightGrams: 2700,
    lengthMm: 360,
    widthMm: 150,
    heightMm: 40,
    basePrice: 1804.8,
    costPrice: 1128.0,
    leadTimeDays: 5,
    minimumOrderQuantity: 1,
    safetyStock: 8,
    binLocation: "Aisle-01-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0091",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-091",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.191",
    weightGrams: 2725,
    lengthMm: 362,
    widthMm: 151,
    heightMm: 41,
    basePrice: 1822.72,
    costPrice: 1139.1999999999998,
    leadTimeDays: 6,
    minimumOrderQuantity: 2,
    safetyStock: 9,
    binLocation: "Aisle-02-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0092",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-092",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.192",
    weightGrams: 2750,
    lengthMm: 364,
    widthMm: 152,
    heightMm: 42,
    basePrice: 1840.64,
    costPrice: 1150.3999999999999,
    leadTimeDays: 7,
    minimumOrderQuantity: 3,
    safetyStock: 10,
    binLocation: "Aisle-03-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0093",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-093",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.193",
    weightGrams: 2775,
    lengthMm: 366,
    widthMm: 153,
    heightMm: 43,
    basePrice: 1858.56,
    costPrice: 1161.6,
    leadTimeDays: 8,
    minimumOrderQuantity: 1,
    safetyStock: 11,
    binLocation: "Aisle-04-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0094",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-094",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.194",
    weightGrams: 2800,
    lengthMm: 368,
    widthMm: 154,
    heightMm: 44,
    basePrice: 1876.48,
    costPrice: 1172.8,
    leadTimeDays: 9,
    minimumOrderQuantity: 2,
    safetyStock: 12,
    binLocation: "Aisle-05-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0095",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-095",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.195",
    weightGrams: 2825,
    lengthMm: 370,
    widthMm: 155,
    heightMm: 45,
    basePrice: 1894.4,
    costPrice: 1184.0,
    leadTimeDays: 10,
    minimumOrderQuantity: 3,
    safetyStock: 13,
    binLocation: "Aisle-06-Shelf-6-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0096",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-096",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.196",
    weightGrams: 2850,
    lengthMm: 372,
    widthMm: 156,
    heightMm: 46,
    basePrice: 1912.32,
    costPrice: 1195.1999999999998,
    leadTimeDays: 11,
    minimumOrderQuantity: 1,
    safetyStock: 14,
    binLocation: "Aisle-07-Shelf-1-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0097",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-097",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.197",
    weightGrams: 2875,
    lengthMm: 374,
    widthMm: 157,
    heightMm: 47,
    basePrice: 1930.24,
    costPrice: 1206.3999999999999,
    leadTimeDays: 12,
    minimumOrderQuantity: 2,
    safetyStock: 15,
    binLocation: "Aisle-08-Shelf-2-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0098",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-098",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.198",
    weightGrams: 2900,
    lengthMm: 376,
    widthMm: 158,
    heightMm: 48,
    basePrice: 1948.16,
    costPrice: 1217.6,
    leadTimeDays: 13,
    minimumOrderQuantity: 3,
    safetyStock: 16,
    binLocation: "Aisle-09-Shelf-3-Level-3",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0099",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-099",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.199",
    weightGrams: 2925,
    lengthMm: 378,
    widthMm: 159,
    heightMm: 49,
    basePrice: 1966.08,
    costPrice: 1228.8,
    leadTimeDays: 14,
    minimumOrderQuantity: 1,
    safetyStock: 17,
    binLocation: "Aisle-10-Shelf-4-Level-1",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
  {
    sku: "SKU-AUD-0100",
    name: "Professional Broadcast Audio & Mixers Ultra-Duty Model-100",
    department: "Professional Broadcast Audio & Mixers",
    category: "Specialized Hardware",
    hsTariffCode: "8471.60.200",
    weightGrams: 2950,
    lengthMm: 380,
    widthMm: 160,
    heightMm: 50,
    basePrice: 1984.0,
    costPrice: 1240.0,
    leadTimeDays: 5,
    minimumOrderQuantity: 2,
    safetyStock: 18,
    binLocation: "Aisle-01-Shelf-5-Level-2",
    voltageRating: "12V-48V DC Low Voltage High-Efficiency",
    operatingTempRange: "-40C to +85C Extended Range",
    complianceCertifications: ["CE", "FCC", "RoHS", "UL", "ISO-14001"]
  },
];
